title: Hype Juice
author: Patrick Robinson
email: propatrobinson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A news site that rates upcoming movies, tv shows, video games, music, and more.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
